image: node:16

stages:
  - npm-install
  - test
  - build
  - deploy

install:
  stage: npm-install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules
    expire_in: "1 hour"

test:
  stage: test
  script:
    - npm run lint

build:
  stage: build
  image: docker:20.10.16
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

  services:
    - docker:20.10.16-dind

  before_script:
    - until docker info; do sleep 1; done
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"

deploy:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config use-context polynotes-mmdj/back:polynotes
    - kubectl rollout restart deployment polynotes-api --namespace=default
