---
- name: Add Secret
  ansible.builtin.shell: |
    mkdir -p /var/mongodb/pki
    echo "{{ pki }}" > /var/mongodb/pki/keyfile
    chmod 600 /var/mongodb/pki/keyfile
    chown mongodb:mongodb /var/mongodb/pki/keyfile

- name: Add Config
  ansible.builtin.template:
    src: mongos.conf.j2
    dest: /etc/mongos.conf
    owner: mongodb
    group: mongodb
    mode: "0600"

- name: Set Permissions
  ansible.builtin.file:
    path: "{{ item }}"
    owner: mongodb
    group: mongodb
    recurse: yes
  loop:
    - /var/log/mongodb
    - /var/mongodb-27017.sock

- name: Start mongos
  ansible.builtin.shell: |
    mongos --fork --config /etc/mongos.conf
