image: node:16

stages:
  - build
  - deploy

build:
  stage: build
  image: "quay.io/buildah/stable:v1.30.0"
  script:
    - buildah bud -f Dockerfile -t "$CI_REGISTRY_IMAGE" .
    - echo "$CI_BUILD_TOKEN" | buildah login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - buildah push "$CI_REGISTRY_IMAGE"

deploy:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config use-context polynotes-mmdj/back:polynotes
    - kubectl rollout restart deployment polynotes-api --namespace=default
