services:
  mongo:
    image: 'bitnami/mongodb:7.0-debian-11'
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: 'polynotes'
      MONGODB_USERNAME: 'polynotes'
      MONGODB_PASSWORD: 'polynotes'
      MONGODB_ROOT_PASSWORD: 'root'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s