Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"

    (1..3).each do |j|
        config.vm.define "replSet1Node#{j}" do |node|
            node.vm.hostname = "rsdosh1-#{j}"
            node.vm.network "private_network", ip: "192.168.121.#{j + 2}"
        end
    end

    (1..3).each do |j|
        config.vm.define "replSet2Node#{j}" do |node|
            node.vm.hostname = "rsdosh2-#{j}"
            node.vm.network "private_network", ip: "192.168.121.#{j + 5}"
        end
    end

    (1..3).each do |i|
        config.vm.define "replSetConf#{i}" do |node|
            node.vm.hostname = "rsdoconf#{i}"
            node.vm.network "private_network", ip: "192.168.121.#{i + 8}"
        end
    end

    config.vm.define "mongos" do |node|
        node.vm.hostname = "rsdomongos"
        config.vm.network "forwarded_port", guest: 27017, host: 27017
        node.vm.network "private_network", ip: "192.168.121.2"
    end
end
