apiVersion: v1
kind: ConfigMap
metadata:
  name: polynotes-api-config
  labels:
    app: polynotes
    tier: back
data:
  CORS_ORIGIN: 'https://polynotes.cluster-2022-7.dopolytech.fr'
  PORT: '3000'
  SMTP_HOST: 'smtp.umontpellier.fr'
  SMTP_PORT: '587'
  COOKIE_DOMAIN: '.cluster-2022-7.dopolytech.fr'

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: polynotes-api-secret
  namespace: default
spec:
  encryptedData:
    JWT_SECRET: AgA6KzORH3AmnJ4sDGSF0WECnOsP16cYLmt92ySCFUSvuEtZ9BcgH0aN1fnfkO6D6NRHN01o9YGfbXYGvn7o+AwPbwFcx7PNIaPcRq++7NlaR3jGJkTNm50vEJV5OS4lLV/KCX9DbbttgHZWbHZxcUtYxOH8Xk7fv9Yig+yyZ1Z6OboB0L9QBtMBc0+F2JWfNmz38nHl3GOeL15LM2kYX2966eX8y8XCcZ3OApI2jBysb7FrRtQ+Vjg+GzUYHlOQjOIyEcR45AL0c6FKpy5ehvDGXAn5UOTitcGwx+5TYRBYZdxkPRBONPH8cZaNmhsfSOl3o+yg4ibBm9N8WgmGyKqjGaDI45TXhO8OL/fU/SfPe3ox37QVk1ddPZd7CvXGuWjwIA5tKq6pX1btXvIHiEbVjbfsm0l4kcoyV6hXZkrNtiWnbY2sgeEJJieooWfyLIChibumLv2B6fE3eAZJbyfMgueKfUxgBmi9+oTFrfpCqDccn61rxknb3EnfTXhJdMFfBALmSnPskdMLfJElv4oQqS6Gx4wPz7ddRVIiu7fiJRpB6d1aHRNS9tdtgDAYnA6QW2ODSxp1M7Y4ivIwXEkTuDwHJuJRzEJkqdaudoWZS0uE1R22c8fUPGOBO4Puq5XPP1VrYRuPuygmZ/JB7tvpjQh10Pnk+I1sWT6aFwVzHEyGSjdWDNk7VbOhdM/zkZWdhYDgV/AgovvSMM7d+I3V+h6/5DdTU/JUQl1W+pDhXVEO/5BJEsDokGlRB1Y2Hj7vLBOR2jEQy5DT82FtO93T
    JWT_SECRET_MAIL: AgAjkSkWc3xCmJ2YlN/OYIzZE8/5sUvj+BFOShSUNNxxzKR2rAXfcmxuyUWSGlMcCAz0G5q12dCx4d+/5RkDIe5eR3yVRpic9PONSJvexZk7Kcn0CwzWQeBS2kK5uxn2U43JSWfooQPceyYksMFB8zBVN1Yk9EliwWog40Q//CkKzzhAK4W0eN8Ekq2F2cWI0CAQzPm9fHyn7FStO53JFqnl47W+0B4IBPw0QZ+/iK8rMll4Z4wnK7Kd5lhaj3PqCNPtUYFDbb678q5LBWvDO5OczTSCRENl/nPI4SbnUqeOpITwrWU37JbYXooRihXf23wnkRCFlJj2m75trCPUnejL0GBGNOt8KNcsZXmy8LsqZiU+85GcTblX3k/Ij2T5W5UpX0SzmLXLssJ81qtjnSSfwC2KerN5YW1MX9wcnOABeX8AY1IrNPc9IGIg4XUv4j68gLwYgEvmQ+b0ee12TMfQYuC3Quxdxm+nixhiJrN89C36JPh5lHQmMsKJlrQyOCHkUbwHWG7NYJ8Cb1p3CwbLeuwjgkIWWM73K40AAxSxJKzX/PH9fmYTvCnlJdT0aolucpr+RCx9sopzGABwpCwaIcbEGdiveGmQaLsWlxeDhdcnUeXclNJEsx3Efi7yQzbFEXpaCb5Epqv7nebrzTJ/n5sQAwgSf9cITNb/arBULRFhyV5PoS0HiF46UYA5ffvhqccjr1rlIA2OU9ct7d3XqP9qgkT/DA9AqJkCbad/5qliqnTsXQ4v27NIp3OWjDiuLgiGE5beAlkjH97VrHQU
    MONGO_URL: AgCIkxafTQoZ3skmIULu22//bOK40CTr/foejZ8CCrOdHVv6EjjaWU4hl3vT5VH5r5gHUEm7Aq3Y60+ZKP8K33z3d8hWIOl835nCTUg4uDdA3taY25jPHopHkB1M334O5XRXaivJwRktMvu8qb4+KvmK7D91BembZWj9D67iB3HxwcpCkB6YH7he3Rxofo8ff22rEo+3ZDr+UC3ZHYJlpswBtwblQpjXTnc7gaOBsv1WehfLcJbxP7iaPMxOmLmNgI4DQZ+IG4+pWh6vQzNN9fkZdAhUQPu4C9FKt7RtHng+6gm4/aHoqYMZ+QF2k6+JmJQG+qTpbUeujuaDCdhkdOai0aps2zIiMNhYfBWJ+9vqK5NBaCHC73Dph/obHvkjDosstiXoq9ixPXEyh8TD+f2t3futeDaZmjzfgnoCWl5hCrclq4R+L2AC8A2KLaSqafPRlV8N/o3lOpKGq2VsSx1F1+eT46hCZ6Xjpa3oJ+MDI0b0CUn2dZRMgaCjreUbV5L8YyaNb0cR/zRtLQuRMpoYNcJ/mB9rUoHKTCaEx1z/7GY0dV7M5NZBLPDn+KTr8YI+bH/3erLx7uHNllJRbry54jie07qYry8r3HfehWtGs2gP2JshC0Lw+X+QznSIVtJoNh5OpuJd3w9pwVHBsA5V2wZXbRPnr1NbupJc829PX+L20ENiLFr8H3Y1TuYTsPeJSOe6a4p7vBq7IfOf2R6zPgPUclsWcjV2L8TwhqkufXh9b/RBsqiSR+aSHx8HuBvDZ+gI088QUlP+ru5HRj0AOMXfxuvAHH2WqT0aXrEozCSngFE5y7cpcXQzAzRVwdtwFVBglSBPWVMo3+n+QcRZZseDI8wxUmuyxo7Rq6EWVbqLnQ==
    SMTP_PASS: AgCjBEn+fIs6Pr4iQRT9l4EqJQTi33XECAFoW8/AWZjOYZpOlXucnCW/LH+pHhh81mxmN0Jjq07w9vbUi9CTkqeNlvjhOcy2cuuCVNduKATxykFAFRSDLqu8Idf+ny9k5aWvRKzyVQ/+9vQ80qK2WUzoH/xSLpfn5/GIN4QdEMd3FKi90RVtLcaybImwATnZ0/kfhKPrmN7a7Fw+Z7sNkFXegG31NQVK+EOCiJtx//fv7wRjZ1Aoixb9fsT1qOfNDU16ibczMlU8hU5XwVPquLVlWmXq/IitFc/qss48B45PHgEzZ5KscZejGC88yzzwIpyNM0eo3/7t9/6DvbyqJm6yb3XNW/kZ5hBzhAK9ZkgzdSmM+o45QNXd7OglPamn6b3ENvIi/UiHH8K9lZKJFmEbNEtWc7s/HDzOAfUfRCZFOuQGGMwAuMZN99kf5CD4DrQplsXIn8vgzSKc1+oumJTpsWYYTXl+kNVDtiJHXsv5lujHJ2iTZuPqxRDv9+Jn9tPhKrNbAIpYPoFcQbhspcNCg9uNt30NpVv0PONFkV/ztD9QbBBDMjDBdjpsTnHjWmvPyFFm5xEKAV0IjqpkGD4iG8GeyKt3BM8amuzfP+7ncQqvs2kUDJohNbfqAi3Z58IuZRGs7OFvFdbS5q3VIb9DHYGEaOpAXUOrWcFVNKR5r0/TyA1/4vDP9F3ixIULkIm+9GUZmdWSkmHMnBEc7J4=
    SMTP_USER: AgAwCFc2KsdyTBxO06IvTZp5Ztr9q9jPnaVnfBCZF+nqiQcaWFlQAE/gXd3bPembCqO92+C3f/EWPq5P2rdXBbahCb/Wb/H1PrjHJoJYJNLlcGgfU02RGbeFFNl6ZpAJoOBl5b3uVa/hjoRLwzaTtQLn/wRSb+4zAP8By4nXj+j5zXxFI2Nq30yjh6azFkC+2GzCoh7SNKxOdq5Rbznf2QWr3l4BA1HUcg2WO8yu1/ZiwPN7t0m+TX3lkHGVLJRz6W5GvsdvPNWRAqns4zNh+YeX9xPBOgtbciv5kTe19Aweoqb9qWFJGAwCt0pAx1VnFMYIylu75GQ4M5ZwCZ9lvs74wjxdfYMVrEJeyUGy4iAGdINWc4quAYEQRaQpdUoZJZSqfaryaqh09T1dOv5zC54fNkjXbwcr3Tz8d1xxITvbDkiBT0n7286t61as0Bskf9Luz/b1Mze4AkDirh6Sgp1OQSetAhixBcfsF7YOcVoaHhj6peucCIH4qviYneiRyD4gRqpDDuVj+DlWsDj/gzXJbTeCYNaPNp+B4Poqhvz6/phh8i1FKIvlzLgRMRyOWxnKSfOr3VxbFst/4jkL0JKqDQ7ZNl+a2tzNSJwdNj4gjkvGTzQjj7AE3lleANPyVq9fkPWJa8pdYqXoUSOjJsttvE2c3G240/6TfYW6wT8YrdO352tJ+Q3LwUFj9RErHiCXyYbH+9sT5kOlyTvx/D9y7YO7z1O5kUtBmyn8DSriOJFByyZo0wtZSRZV
  template:
    metadata:
      name: polynotes-api-secret
      namespace: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: polynotes-api
  labels:
    app: polynotes
    tier: back
spec:
  selector:
    matchLabels:
      app: polynotes-api
  template:
    metadata:
      labels:
        app: polynotes-api
    spec:
      containers:
      - name: polynotes-api
        image: gitlab.polytech.umontpellier.fr:5050/polynotes-mmdj/back
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: polynotes-api-config
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: polynotes-api-secret
                key: JWT_SECRET
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: polynotes-api-secret
                key: MONGO_URL
          - name: JWT_SECRET_MAIL
            valueFrom:
              secretKeyRef:
                name: polynotes-api-secret
                key: JWT_SECRET_MAIL
          - name: SMTP_PASS
            valueFrom:
              secretKeyRef:
                name: polynotes-api-secret
                key: SMTP_PASS
          - name: SMTP_USER
            valueFrom:
              secretKeyRef:
                name: polynotes-api-secret
                key: SMTP_USER
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: gitlab-registry-secret
  replicas: 2

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: polynotes
    tier: back
  name: polynotes-api
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: polynotes-api
