---
- name: Install pip
  ansible.builtin.apt:
    update_cache: true
    name: python3-pip
    state: present

- name: Install pymongo
  ansible.builtin.pip:
    name: pymongo
    state: present

- name: Create replica set
  community.mongodb.mongodb_replicaset:
    replica_set: "{{ mongodb_replicaset_name }}"
    members:
      - "{{ hostvars[inventory_hostname]['ansible_host'] }}:27017"
      - "{{ mongodb_replicaset_member1 }}"
      - "{{ mongodb_replicaset_member2 }}"
