apiVersion: v1
kind: ConfigMap
metadata:
  name: polynotes-api-config
  labels:
    app: polynotes
    tier: back
data:
  CORS_ORIGIN: 'https://polynotes.cluster-2022-7.dopolytech.fr'
  PORT: '3000'
  SMTP_HOST: 'smtp.umontpellier.fr'
  SMTP_PORT: '587'
  COOKIE_DOMAIN: '.cluster-2022-7.dopolytech.fr'

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: polynotes-api-secret
  namespace: default
spec:
  encryptedData:
    JWT_SECRET: AgBfapEA+xlhyY9yjAKWlHVNgRH9oY0PrRXT2DDE4vkN7IVSi17RLQoydPW9fy6rJSd1wdG5mz1mhKkiBedalArFqbfJHKmSN9vNXQmEOoKsn2h66qb5ksoENVNRg/ONzZCzSpRb2yi58MWGFgUpZDE28g5FIl5q/QryBAdg42HOR7B+mb3nZOqbx1Q/8S6bT4KO+R4d+AnyQ+H2DtI/WApxw6ZeqLyxW2fd2ey0k9Ei5vavMY2T3cgJQiWqom3tVta/Rw4CEn/KryXkCn4vIxv3RHUjiiorkAXunYXaN9O3xk84yQYOjTRVpg6EoOifg28cCcEgoMDkuwLc62pWAHAaDyQe/hS16kcXi5hSmITD0lZm4wCUEVd4FzdAKnpcyTL8FrI77vyvCu9DWdWuBUvgOzH7uAjEoS7c+pqNdgiANg0RV8KW985Bb7oCklV+0QR76fZJz6BH/DP3YK8yb55n7mR0Inm5iV2Og2+JWlYMOUoa8gx+69mqvk+D9Gjb1sv2UOUuXUn0xhm7I3Z4plLNfqzGGUnAmM6FXKH2LLyDgSauNinbkaDUSJi7JnkWbSUBn3hgsDCsDU5NzEm442kLOuAM8GfigZFKJzRxvvdhLOG4jN1q2Cf+mr2L5vfMPjV7qdVSc5AyVU87+LYM9wPXJjirYKiJZKyPv+2NoCrGHKIn6JmBTJiN5aumiP/Sin9GXCDSmBkrXp82KAd/B4+Oo4aPcAbw52xq1/A+lFM1Prbzu3OPJJDEqqXUUMcADocJdRTKH2T52+odc4TUkNmx
    JWT_SECRET_MAIL: AgBe3G6E6gJlOv8mKK3bcSuc58hnKW79PUW2KxDG8SIE0mxjDLZFsDF0ngGT94oXlTwm+MG2Mlzh5zdiV2wkIWLp+Prvt9akbvhjyVU9UvkAEPEbNCCe1JGxZEbqjYZdXxe01xqp0wDOahh1sgcqVVSDd20brbKPP0ED+xyMfm7ghWljioArrHcsbFM3LzEUgVz6yfrk+B4hrZfSvVuORRUhRKcXcEdloJtdzEx4ceFCEQ2fCHYLy1/h9HnoHwBO4b91uliUvAaJL6J5SSrMpZYlpnmx9ZKn8ojv+Vu7xKma3L17y6YWkYRPXpDvjDVIxVfWecbwmJUtvaViUuKuG0dM4ifDiSRQvSkNQWf/9r89uhN5mknzF30kAti4vvj39dMZ6DgMqTkgsLgDg4OQ/Ees67HCcYL3UMXbVue/NgBS5afzVPACmYg5FAoHNYYZ/SuCYB1QLtRA5pNztb6CwH6WKvM0QYIjK40hWlKHEC7E/g7vPacx7AOAcpPoEEWPJqhvAvAb+2+sDSkF8ThA5gyKSOLynmEsSTRlG3mudG0k6YrSFKnkXtCZra+g3slpmPvP4BIHIUqUrCHY01YVkyRSqk2EWLpDASmPY9j0rUhEL+/O5NaN1WMfzh2Tli/AgaXFDEGDGtxSBas0s4rdQLpT/JVJIR2vqpnO3NFyIGrw8cMqtIGAnLJY3WNdeSENuJG82aNT9JKfDCLhPHKOraxFHcwoYHBuNuLXzz/2N5DFfNfJwgTqma0rZ/TMLD8ZYdVcovDzyKANFyuYpT0Cqp8yRg==
    MONGO_URL: AgCRQ6uo6PmR6CeeYeyrRFAAI6YaxYBgwcOVP+LiRDqYeM/ElDj2eAeSBNX9TsTvOxP24CGlSdkhUAF4QhrqLPGiT4QNR4c2hGuQg6gzfOJwLA52lN/jw8nJSxij6xQINsIL5vpoxaNOCzz28YOAWjjcGlDLf+AO+tUBXHcpl721JBxEPBTFS3yoz15AIFsBnacQJ23EoOZ7CHV2G+JwraImjoq/J9c1Y1oo6C24+LWkOovIqI2ccdseYWwtOfLPIfAl6M1KBJmTESM9FwwBqtBQKHLGVXCqp6ZfLwn0L4uEJ61cfwujAr1+x1SPjfRY2ahza/5zs+nQUoiXahiFveGZ0DYHQWYXfCCI0e2hXOQz7mZnVb7TZr2H/mYOSDHjoPHyMomV3TRAPpvE8R6BTgHd+JoQ+3LQDrs6ay/lYj/JYQCHB8mI8TGptTsXKUlK7DrRh++fbUcrcAuJc+O3RFk8jF/enRvHZ60SJASb3hlUKKQFr+lFpH818mVwgs0pI5Dq7swbYoCNmHSqxTZ06OiBdOWnl93Y6KVQJE+R6evX+OXOd/5GuTx5+KSpeZkpB0cUQOVBHf0GZu1K1nc5ff2qqOo+1FIuIyZhdOZeHOpbNgiNaeYxpDBe/qmokmOWI3f50nzrSCl3hGyzOAs/aC3EBV1VP+DVwfUUmgyWTGgw4j3MfJ3q8m28gLuSg+LjGPi8kbEDyqhR2B9LW2EPfI03O7HP2saeQ+JzZp9KmpQcnUdd+ed/eCT3/coBNbzcIx0ry7BM7w9Iaymz6yt31BCGXnqEDfPrdyRhi1hCiRUTjT21cXPu9TmdCvBMcmOjZZqwrFrNf/tvnepNPx4a
    SMTP_PASS: AgAf5MANEw4exQjKfQ2/Q9rXuK9tQVLDs6IPRQXaDE91Fax85wYQ5h+IRbuAeBsJ8Q3OxFF77owsd3gRdvw1X5CSGlhqY2pxSSHrvgOXwO5vg9DNjEz/JN9DYt60ZLs3F1RpZUd6lbuynIwWY+LF5lm59aKNVlckpvJY0E2mrYvbW74DrCqSrMjwIZEFfsFyCv2S3c8tlZMprgQfJ2mZ9J1kJS5ddEeZnu1T6WFp7yq57ZRLjwQWKzuaX7AO0HZh7ExBTgp7n76keNOAVMu4ol9QrSAri6BlKzB/qCTWPbNgd0ytbQEvo80F2ZVrTxSxffhWDWmer+SmnEa9Y3247yTmfbCJy5oF+DN3grFBCFbrjwbOYFyasY8Faa1PvSS4JcwuSeMEd/gAkeMB6ZweWSdjJfWrsQs+0yraPsNDl312eMwxb6YHtTc/QEBWQfKTf4OLbswBe7/aq+cg84nA5vhzHL/qVsL4iPqYyLgpO6qKP6S43b6g/+CFnWFue/WJhX7VmLEBJtdBEuHQPGq6n1/QOdKZpkwn4pSho/9RFcXfKcBySxkvX7t+bOVdU4VGcwiqTdNxSzZA4coibUHoWbUQziP9weOk0gqQ8FX/aqIgLTX7koaCHfbIvdcCd4R/dkhuYvm/DuhoeuUu5CqxOKqRLAMPj/9wjMbOh0Dizu0Td8sq+wNZBkiJyX8UQKYkSBS6tlpDgWWqtcCptIF1zPw=
    SMTP_USER: AgAS0rB2Kd9dvChrpCOEqecwXNyEyMKEe1AAkc0QEBk6T9bDVWBw6d0FRyKCDgEGuOzTr8q/hERtqPpBSA8rZC2+k4wWEPrFlw92J8NDm+l0eBKLGe1HDJuT+lwmnVq50h8Ui99V3NfkNflNniwJvY5O+hhBPBx74dUcg192Ly3jxUyGuAJSRyk0E8nAY9HNRtz/4pQwuPn4F4JpKbgiyl2gnKvgAn4yjQW6vSI9kgfYO7tX0qiGopj5SmBTO9nDPdE+MK5jC3SwwVoPZeTqciKGQhyNbBsZAi1axvv5vFN2CEnPKf4IXcMhOaSQA1FlE91pmAv1BvlF/EdNIEamKb7BKaQ1kqYe63DAHgOzXlXkci56bMqPDhKrHGPYLQbD8TR08B32jlStssBHL6o4rbwt1R6n2LSKgRd9eJV8kkpQ50eXToGovA1miVJ/UBmeBHAL0gNHwCBS/fXpwGOrrVUlR3HG8r9hEy0fCI2DR5KSwjJ+x8L2rkbg6XVV5u4pQJxpbYRt2PORHwD+ZqHJSex4Wv2QXsfUOH3oaZCr1tijzrA4Al+3EfAnDgO571eSED6UX5vdk0Xc7RE0DDKB4mi3/gtugGuTqlB3VjYSmL7wPrVHmhkwIi8hfVz8QsJITqXP8VuuA0XdeG5LJ5fYfSNxmaedtjkr5lGeDh0LnklJp3sQKLYz4paOXSbx3HtboykSdIupGfnf3H9C2/ovuhK3zJcyC8g5Tu33juE07GOzX/vSUZSESYIWK+2m
  template:
    metadata:
      labels:
        app: polynotes
        tier: back
      name: polynotes-api-secret
      namespace: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: polynotes-api
  labels:
    app: polynotes
    tier: back
spec:
  selector:
    matchLabels:
      app: polynotes-api
  template:
    metadata:
      labels:
        app: polynotes-api
    spec:
      containers:
      - name: polynotes-api
        image: gitlab.polytech.umontpellier.fr:5050/polynotes-mmdj/back
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: polynotes-api-config
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: polynotes-api-secret
                key: JWT_SECRET
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: polynotes-api-secret
                key: MONGO_URL
          - name: JWT_SECRET_MAIL
            valueFrom:
              secretKeyRef:
                name: polynotes-api-secret
                key: JWT_SECRET_MAIL
          - name: SMTP_PASS
            valueFrom:
              secretKeyRef:
                name: polynotes-api-secret
                key: SMTP_PASS
          - name: SMTP_USER
            valueFrom:
              secretKeyRef:
                name: polynotes-api-secret
                key: SMTP_USER
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: gitlab-registry-secret
  replicas: 2

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: polynotes
    tier: back
  name: polynotes-api
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: polynotes-api
