apiVersion: v1
kind: ConfigMap
metadata:
  name: polynotes-api-config
  labels:
    app: polynotes
    tier: back
data:
  CORS_ORIGIN: 'https://polynotes.cluster-2022-7.dopolytech.fr/'
  PORT: '3000'
  SMTP_HOST: 'smtp.umontpellier.fr'
  SMTP_PORT: '587'
  COOKIE_DOMAIN: 'polynotes.cluster-2022-7.dopolytech.fr'

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: polynotes-api-secret
spec:
  encryptedData:
    JWT_SECRET: AgAOZaakwZEc2R+4h+h6aUDBepET6yLjeBTiI8frEkJyBtmQag5SnrPiIBFTBUe+F3l/gQ4wfVR7bUH7DyrQjm4Dos8iG1WpgG8FNp3JLHNM+PgkmqRB1JMHpEFD/x4tqTx8Tw66nfeGdvEeXeNQLLVPUX7E4Pe/66VxiedNuDu7RHsdPbPlundzp44ObayJIs1GOfteer8kN0ga6E3ufGLhJLtW0sTgxYbAsLkVhTyoYPr7KtxhnfhaGEJdDGdOAm054yX9CcteYeQGIqs25GipvOv1+cVgpykQKjNGN24BAnGTGN/u4b2YqUh+qmp/c45gymb5LH69eHfK4pBC4stQ/BtWcrTjnnsCROyegdHTwQztueSB6MJn7MrN6SDGFRy/3HR2LtTn/Bpvn/bzT186115wqeJ9JJS+w7/G6JvquXYi3P0jk3yUqLQfGsoIqw4rU2Reqwvu50O+kbit8FdDMThsDq1axUoMFPiYlpNIco0fSBEOGJD6IJ3so7vDn832F8hkykPm9/xWfNmjNZmrzfxEgUKu9Hjpw2fOWJEIYY4XS1BX4JQjXo1H0/ftPQradzhYCp3Rc8JAHxdb3J+JJhdf0JqpEfxbccsKVgZSuJ2V/CfXlHQqwDcoF85Qb/M/IIB4IO7DutAAz5A0/l4N/SOyIDWRxBsCCQI0PlQ/TJhA38iuizcPuv7wUnwupY8gGpOxG84Ovgxzctp9Vt92TQq9FXVB+OIAaCWUiW4ol1GPkZ3kT1+nwAV403OMHlS3JbI//G8utg5poTxGnUaf
    JWT_SECRET_MAIL: AgBc0Snd4At1GdrXFRO4uKdDt1z2bRQxyqLxSnAF31m3/23l8vUnSa/HYx5RIv4DJVmt5HSOFfrC4nQzzX6m9V6gQGfbO1L45a+4Y2Sqb5keCbYT7iKQVpmLv1+cqVfRP1sB/xafldzKtjOlybZd2wngHLCoUHZYa3HXQHn17+jX076VX/yKphC2nO6C6tT7/pRQ7UFCScGX9NT4OfKOPF0GLiZbj1tfLCaXO0ZjkNH7YXEOLq6t5lCaP25wCXRv3pAUvrlYW9UP/r4W1RxvBIBQQC0WfM7on5DFVCde2JfWdI9hDsZ/f3R+qR0E5QEEyTFCbFULLroVtXCgPpOx0PX3iQpqbQ0+gzVEq8Os9+Tf9vbjlPAbGOLAyj/urbxyckkHuudqRg+Oeb9/Wm8WaxoizguKbFZD13H1f/TNSBg/TGc2+/2mzzpQ9tQu/d4qUT9+f0LPEsABnoytu7r70jsWWmtSVVV8ZZKtX/KM7DHgPk3nlq15HYNKiwqBXlq/ivRrTl0vqJKESM5X1gaTc2bbJUhXABZIp8DU5K8gcMT7Q4QEUSgCQ3GzdpGvbI9wT7cW7InYMSKXf3lWWmC7W4M2q6Cnf0YyJ3KG4N8NqkgBh/BNg7vpaAjuhhd0NeJyigV1OekB7qlTOtAotMtN6yWCVrGTullxEwdCwsoM++no+KS8grwlRJ//bmLmjo3Q+0ajrTLj+Di0MSjUr64MvZaFe+WGIW4GjIJ0kdFcWhjI/EUX3AdInpZBNGyj6FeB4Jdr56Tu0kHaaMUzL0mlIrb9Aw==
    MONGO_URL: AgA1rKZqXwbRE1sNn5oUlslnM6H4mh2NJdP8fNxgdjnWKmVaayhnql8uP2FuNnl2hkAXGDobJPFLmLpLtmm1KuuXX03bMLNMn/c4K57J8L5m0IF64caD0PiGgQWc8QTDHGTB1OUqfA49J/zsUCb0sYgRYlUt9H9NabPBN9Eekj6hU4rJU2pDNZl0EObathvmh2efHWikfUOYmsuMO1sEbqICXZxCmTwGfCbgwj2LUzacTmZk3rbqZE99BltErdgPlz3QHaMlR2oRSyt826kRYDgJI96Aig7E69YDwMH2lWVXYgVBFL9rL3v5Y6fMCf8odQAY8KheSiDB4LMrhGAj590ITWrlT1jQ9se/WX3/pxTa9jJgYXMCEqGmnxXv1MTEkNa7XLsGy0NJ6GpNg1/ve3KwvuR3xrRbX7NtcC3kvpWdW5p0J81GQSRngOturJngRp0U/pgaAJZtN0uodDS+7+FAQcbjab8x399mQd3Ua78uUsz9MmUk+/ST6JnisGRZx2jtizjfl8HWXQHMNt6jW+CiSQcr//1nTL+Bgsl33jjOzBcNnPCaxI+1zW4Wnh+N2iboalzlWEUtYIZh3FMjweppE0imdzPPY/HeBB3jepYFcAzypmx53+7QAfFhLOjMO7eHF3y29sJ/DElp9TiZ7I5hg4RxYxTj9bNX7cu0uryzcDDnbha7BK6o4NCGtw3HWyKplnpWAvByHLog+P7eaCiM+PV6dooeO58Z9AShYOGbgQqIxWlGWLn0tcc2Wq+g4GNATzfEXPZK7PJKeWFB3JWa9foy96W7pQPEZDWUKUmYo2wI74WCr5lFD15ZUVIKPfBsmZsqHRzwqGaSCXco
    SMTP_PASS: AgBJri0PN2krO54Ux8Iu/YOdDfhr3UOanf/zMJQxbxHOPfx9LsMwcWbc5s8iDQRgmGI7orSfDpPx+/wszaTzSfJwO6CaA+Wia6vlfNniYYXx8S52qP3WQwr9hDXjYML/kCejpZXy6yORAEjoTTxoID3xS6RhjUXyhuClXaYJGSIf3rsKS1s0yCydogjuOXdIuARGqyOsvCQVsuVvshTNasInyjO+am8yW64+91VnFtZvLK/cEUf93Jc0cmDCsy8MPAcmBlT/cSVdkN4FoVaAC8lDB3SfPuy5YaTjkXNQY1jclZcxo6OaeWSTfVEaKucF2ueEHj4m5caaAs13SXVJ30BqQE5aBxuz+2Rhb/Y7k4IVc0ibgbbS4PiNJgziEIYncRKWtu02xeyPcsWIhNV4cDK153Vzpm8oB4QoDn7eELIAFEKoDc9sFSpIQdrCORboa8KsF5pi+NW+JExzQT13HZNTFUBOrH2Hi6I+uEMr+Uk2GwCNX/uYTNRQvOWjI34I459Lf6DzLbRaVl8rXZ05aMOibCH6+x/RM16P7qfQ3KulOvWjeLTFwEsZ5lzpDb/P/mJbrri9uzxnfk/DzXpgbkwMnP2E2Eh7o5Ev9oSUsRsdvsUAd5HQLlC+6Ekawq0sw4yqoL5xoWbVlv83OIYq8j/m8sNnQvtXMZX4yMlT3eTavokiAEbtw2WR9Sd+6+XzCe5YPj6UHW7QA5CsVbf+8JU=
    SMTP_USER: AgCJH6mmiJYuggZ5xlvtGi8czEc0MmfWxFFUJKh7onhS5tJtA3yLmK1GTwsc2bgCw/29zKFx5gfIqev2iTM4JUEiwP9SnrfycbcIEZiccrVo8QFnBeata6j3nPxtSJgQMu47X/GdOd/lhXc585WmZvY9ljARliq2K/V1PHx4NYzU6HeSWWA/7NE5KCZlBI6cbwCGmWeA/mGPXexjX37U71Od9pGxAF36AUdV0TcJ0BkVU8W4kcW98otnR+O5AOJrcMq0+Z7SL/Rt3vv6sc5+rSGhBFGIccjtbQ9Yr4y19XIvludw/mK9hPPKHJyZA1MpO/OC2qKkaOXxxcCcCyf3enO+0gTRTyH8w2np3CT9zroPk7gSpFkqrOlA5tI+4SGB25oiHAS/t0/INz9TU5S9UswpV2ydWFR88SqXNVRRu13NaJwWm/No9Y5g/IuqSNrRHGxzF3h0axyQgP/lvzsOjermLw5L6+yTztsQDA/oEXwjchGbZ3kFL3zo0lvx8FkKpHgZeRi5rHqP9WaYqloG8vgBkPADzf7fdNfjjm2zrUzCajMqGTLK4md2JUgwBxrs7uzzU2lg8XlsPMMGIl0ZCyF6+rwa9XXJ2zcYw4c20mrsDeMurp+E8wAxRvjDKX+KApjWqbyBPMg+LMpsT/AdQbtXiPq7vQAPtGzlQseXiPMezmUc78XNgVvPYKhHkW5SuKjghCwUU9nPFmDIqirpTKJBzwfKYcZ9jbYLnJ47cb/nRYMkJmNb+cH+GDGo
  template:
    metadata:
      labels:
        app: polynotes
        tier: back
      name: polynotes-api-secret
      namespace: default


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: polynotes-api
  labels:
    app: polynotes
    tier: back
spec:
  selector:
    matchLabels:
      app: polynotes-api
  template:
    metadata:
      labels:
        app: polynotes-api
    spec:
      containers:
      - name: polynotes-api
        image: gitlab.polytech.umontpellier.fr:5050/polynotes-mmdj/back
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: polynotes-api-config
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: polynotes-api-secret
                key: MONGO_URL
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: polynotes-api-secret
                key: JWT_SECRET
          - name: JWT_SECRET_MAIL
            valueFrom:
              secretKeyRef:
                name: polynotes-api-secret
                key: JWT_SECRET_MAIL
          - name: SMTP_PASS
            valueFrom:
              secretKeyRef:
                name: polynotes-api-secret
                key: SMTP_PASS
          - name: SMTP_USER
            valueFrom:
              secretKeyRef:
                name: polynotes-api-secret
                key: SMTP_USER
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: gitlab-registry-secret

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: polynotes
    tier: back
  name: polynotes-api
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: polynotes-api
